meta_product_name: "BAR | WARS"
meta_title: "Bar Wars - Exbeerience Copenhagen"
meta_description: "Who doesn't love a drink and a good deal? This app lets you combine the two. It's simple, easy and dealicious!"
meta_image: "https://imgur.com/JNGBKTi"
