meta_product_name: "BAR | WARS"
meta_title: "Bar Wars - Exbeerience Copenhagen"
meta_description: "Who doesn't love a drink and a good deal? This app lets you combine the two. It's simple, easy and dealicious!"
meta_image: "https://images.unsplash.com/photo-1453825012366-3738046cb6c7?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ff64e0eec4f3a05866458ad6e4878297&auto=format&fit=crop&w=1489&q=80"
